### PR TITLE
Search bar now uses react.

### PR DESCRIPTION
**Pull request by Jpadilla1**
qq1oiwvqth

### CODE REVIEW

**Comment by jpadilla** [comment]
@Jpadilla1 nice work! any setup instructions?

**Comment by Jpadilla1** [comment]
The bundle.js file is being loaded in the base.html template from django. You can generate the file by running...

1. `npm install -g webpack`
2. `cd static/react`
3. `npm install`
4. `webpack`

**Comment by jpadilla** [comment]
@Jpadilla1 getting the following error: `ERROR in Cannot find module 'babel-runtime/helpers/interop-require-default'` when running `webpack`. What node version are you using?

**Comment by Jpadilla1** [comment]
@jpadilla That's strange. I'm using node version 4.0.0.

**Pull request merged**
