### PR TITLE
Docker fig setup

### PR DESCRIPTION
**Pull request by Jpadilla1**
Containerizes the whole application into multiple containers using fig.

Containers:
- DB
- Nginx & ssl (https)
- Django application
- Data only container

Setup

``` bash
fig build
fig up -d
```

To see the containers running you can try:

``` bash
fig ps
```

DB

When containers are running the first time, you have to do this.

``` bash
fig run app python manage.py syncdb --migrate
fig run app python manage.py migrate users
fig run app python manage.py migrate
```

Note: Only downside for now is the db setup. :/

### CODE REVIEW

**Comment by jpadilla** [comment]
@Jpadilla1 cual es el resulting image size? El official python image es como de 900MB si no me equivoco.

**Comment by Jpadilla1** [comment]
@jpadilla After downloading the official python:2.7 it takes up to 744.9 MB (image on my machine) and the resulting image after the build and notes dependencies are installed. It takes about 828.5 MB.

**Comment by jpadilla** [comment]
@Jpadilla1 let's try `python:2.7-slim`

**Comment by Jpadilla1** [comment]
@jpadilla After setting up python:2.7-slim the final image size got down to 502.1 MB. :)

**Comment by jpadilla** [comment]
Gonna close this for now. Thank you @Jpadilla1! We can definitely revisit this if it makes sense, now that the docker ecosystem has matured.

This could help with #94. I've recently been using Kubernetes on GCE and have really enjoyed it. Maybe that's an option instead of Heroku.

**Pull request closed without merging**
