### PR TITLE
Python 3.7 + Django 2

### PR DESCRIPTION
**Pull request by jpadilla**
**NOT READY TO MERGE**

@rnegron Started working on this, still haven't gone through everything but we're almost there!

### CODE REVIEW

**Comment by rnegron** [comment]
Started on some unittests (#16). There doesn't seem to be anything blocking Python 3.7 at first glance. More testing would be good (forms, views, plus some integration tests with Selenium?)

**Comment by jpadilla** [comment]
giphy

Awesome work! Honestly, I wouldn't really invest the time/resources on integration tests with Selenium or with too many unit tests, just cover some of the most critical paths and that's it. Just enough to help with maintenance. Newer features should ideally have some tests as well.

**Comment by jpadilla** [comment]
@rnegron que hacemos con esto, merge/deploy it?

**Comment by rnegron** [comment]
Este fin de semana le hecho un vistazo y hago algunos otros unittests. Luego de eso lo podemos merge yo creo

**Comment by rnegron** [comment]
1 year later! @jpadilla What do you think?

**Pull request merged**
